name: bluetooth_gamepad_example
description: "An example app for virtual_gamepad."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  virtual_gamepad:
    path: ../
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
